# Automate, customize, and execute your software development workflows right in your repository with GitHub Actions.
# Documentation: https://docs.github.com/en/actions

name: deploy

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger build
      shell: bash
      run: |
        curl \
        --fail \
        --silent \
        --request POST \
        --form token=${{ secrets.CI_TOKEN }} \
        --form ref=main \
        --form 'variables[GITHUB_COMMIT_REF_NAME]'=$GITHUB_REF_NAME \
        ${{ secrets.CI_WEBHOOK_URL }} \
        &> /dev/null