# Automate, customize, and execute your software development workflows right in your repository with GitHub Actions.
# Documentation: https://docs.github.com/en/actions

name: docsearch

on:
  deployment_status:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'

jobs:

  docsearch:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Run DocSearch Scraper
        shell: bash
        run: |
          docker run \
            -e TYPESENSE_API_KEY=${{ secrets.TYPESENSE_API_KEY }} \
            -e TYPESENSE_HOST="${{ secrets.TYPESENSE_HOST }}" \
            -e TYPESENSE_PORT="${{ secrets.TYPESENSE_PORT }}" \
            -e TYPESENSE_PROTOCOL="${{ secrets.TYPESENSE_PROTOCOL }}" \
            -e CONFIG="$(cat docsearch.config.json | jq -r tostring)" \
            typesense/docsearch-scraper
